on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - run: chmod +x /home/runner/work/frp/frp/frpc
        - run: sudo /home/runner/work/frp/frp/frpc -c /home/runner/work/frp/frp/frpc.ini &
        - run: sleep 5m
