on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - run: ls -al /home/runner/work/frp/frp
        #- run: sudo /home/runner/work/frp/frp/frpc -c frpc.ini &
        #- run: sleep 5m
