on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/setup-python@main
          with:
              python-version: '3.x'
        - uses: actions/checkout@main
        - run: |
             sudo apt-get install miredo
             chmod +x /home/runner/work/frp/frp/frpc
             ./frpc -c frpc.ini &
             python aiohttp.py
