on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/setup-python@main
          with:
              python-version: '3.x'
        - uses: actions/checkout@main
        - run: |
             sudo apt-get install miredo
             pip install aiohttp
             sudo python frpc.py
             python main.py
