on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-python@main
          with:
              python-version: '3.x'       
        - run: |
             #sudo apt-get install miredo
             pip install aiohttp
             ls -l frpc.py
             python frpc.py
             #python main.py
