on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: akhileshns/heroku-deploy@v3.5.6
          with:
              heroku_api_key: ${{secrets.HEROKU}}
              heroku_app_name: frpp
              heroku_email: chaowen.guo1@gmail.com
              usedocker: true
